path:
  root: ./
  experiments_root: /PATH/experiments/VN_x4_d4/model/
  training_states: /PATH/experiments/VN_x4_d4/training_states/
  models: /PATH/ResearchSeminar/Training/models/
  log: /PATH/experiments/VN_x4_d4/log/
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

name: VN_x4_d4
model_type: VN_Model
scale: 4
num_gpu: 1
manual_seed: 42

datasets:
  train:
    name: TJU-DHD_traffic
    type: PairedImageDataset
    dataroot_gt: /PATH/train/dhd_traffic/HR
    dataroot_lq: /PATH/train/dhd_traffic/LR
    io_backend:
      type: disk
    
    gt_size: 128
    use_hflip: true
    use_rot: true

    num_worker_per_gpu: 4 
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1

    prefetch_mode: ~
  
  val:
    name: TJU-DHD_traffic
    type: PairedImageDataset
    dataroot_gt: /PATH/val_small/dhd_traffic/HR
    dataroot_lq: /PATH/val_small/dhd_traffic/LR
    io_backend:
      type: disk

network_g:
  type: VN
  depth: 8
  scale_factor: 4
  num_channels : 64

train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
  
  scheduler:
    type: MultiStepLR
    milestones: [35364, 53046, 63655, 67191]
    gamma: 0.5
  
  use_amp: true
  total_iter: 70728 #50 epochs
  warmup_iter: -1

  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
    eps: !!float 1e-9

  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e2
  use_tb_logger: false
  wandb:
    project: ~

dist_params:
  backend: nccl
  port: 29500
